### ISSUE TITLE
[Feat] SignUpView 화면 구현

### ISSUE THREAD

**Issue by Choe-ju** [APP-iOS3rd/PJ4T5_TrackUs#14]
## 공통 부분
- [x] 프로그래스바 구현
- [x] 공통 UI 코드부분 작성

## View
- [x] 닉네임 설정 view
- [x] 프로필 사진 등록 view
- [x] 신체 정보 입력 view
- [x] 연령대 및 성별 view
- [x] 러닝 스타일 view
- [x] 일일 운동량 view

**Comment by ohtt-iOS** [comment]
💪🏻
